### ISSUE TITLE
Use isomorphic-fetch instead of whatwg-fetch directly

### ISSUE THREAD

**Issue by tracker1** [tryolabs/fetch-it#2]
If you switch out the fetch dependency to `isomorphic-fetch` your module can be used server-side.

**Comment by dig3** [comment]
Thanks for the feedback. I think I'll have to change the `window` references too. Certainly, make it usable on server-side is one of the thing I want to do.

**Comment by AsaAyers** [comment]
It looks like you're using Babel, so you can just use `global` and it will be `window` in the browser and `global` in Node.

I actually wonder if you should even import fetch. Wouldn't it be better to just let the app import a fetch implementation and just use whatever is attached to `global`?

**Comment by dig3** [comment]
@AsaAyers that make sense! Change the references to `window` for `global`, and run some test to verify if `fetch`, `Promise` and other stuff is there. If not throw an error. What do you think?

**Comment by AsaAyers** [comment]
I think it should do some test to see if you can discover `fetch` and throw if it's missing.

Babel can polyfill `Promise` for you.

```js
let promise = Promise.resolve(request);
```

You get a result something like this:

```js
var _Promise = __webpack_require__(394)['default'];
var promise = _Promise.resolve(request);
```

If you try that route, take a look at the compiled output to verify that Babel's promise is included. The ReactA11y project used the babel runtime, but it wasn't compiled into their project and it spawned [quite a few issues](https://github.com/reactjs/react-a11y/search?q=runtime&type=Issues&utf8=%E2%9C%93).
